# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.hostmanager.manage_host = true
  config.vm.box = "sincerely/trusty64"
  config.vm.provision :hostmanager

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "3184"]
  end

  config.vm.define "vis" do |node|
    node.vm.network "forwarded_port", guest: 80, host: 8080
    node.vm.network "forwarded_port", guest: 4567, host: 4567
    node.vm.network "forwarded_port", guest: 5557, host: 5557
    node.vm.network "forwarded_port", guest: 5556, host: 5556
    node.vm.network "forwarded_port", guest: 82, host: 8082
    node.vm.hostname = "vis"
    node.vm.provision :puppet do |puppet|
      puppet.manifest_file = "visibility.pp"
      puppet.manifests_path = "manifests"
      puppet.module_path = "modules"
    end
  end
end
