# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "sincerely/trusty64"

  config.vm.define "app" do |node|
    node.vm.hostname = "app"
    node.vm.provision :puppet do |puppet|
      puppet.manifest_file = "app.pp"
      puppet.manifests_path = "manifests"
      puppet.module_path = "modules"
    end
  end

  config.vm.define "process" do |node|
    node.vm.hostname = "process"
    node.vm.provision :puppet do |puppet|
      puppet.manifest_file = "process.pp"
      puppet.manifests_path = "manifests"
      puppet.module_path = "modules"
    end
  end

  config.vm.define "store" do |node|
    node.vm.hostname = "store"
    node.vm.provision :puppet do |puppet|
      puppet.manifest_file = "store.pp"
      puppet.manifests_path = "manifests"
      puppet.module_path = "modules"
    end
  end

end
